const codes = new Set([
  "TESTNET_ALLOWANCE_CHANGED",
  "TESTNET_APPROVAL_BUSY",
  "TESTNET_APPROVAL_GAS_INVALID",
  "TESTNET_APPROVAL_SIMULATION_FAILED",
  "TESTNET_APPROVAL_STALE",
  "TESTNET_APPROVAL_TIMEOUT",
  "TESTNET_BLOCK_CHANGED",
  "TESTNET_BROWSER_BUSY",
  "TESTNET_BROWSER_CONFIG",
  "TESTNET_BROWSER_ORIGIN",
  "TESTNET_BROWSER_UNAVAILABLE",
  "TESTNET_CONFIGURATION_INVALID",
  "TESTNET_HISTORICAL_REQUEST_INVALID",
  "TESTNET_HISTORICAL_BUSY",
  "TESTNET_HISTORICAL_TIMEOUT",
  "TESTNET_HISTORICAL_RPC_UNAVAILABLE",
  "TESTNET_HISTORICAL_WRONG_CHAIN",
  "TESTNET_HISTORICAL_STALE",
  "TESTNET_HISTORICAL_UNVERIFIED",
  "TESTNET_HISTORICAL_NOT_CONFIRMED",
  "TESTNET_HISTORICAL_REORGED",
  "TESTNET_CONTEXT_STORAGE_UNAVAILABLE",
  "TESTNET_CONTEXT_ATTEMPTED",
  "TESTNET_CONTEXT_CAPACITY",
  "TESTNET_CONTEXT_HASH_CHANGED",
  "TESTNET_CONTEXT_INVALID",
  "TESTNET_CONTEXT_UNAVAILABLE",
  "TESTNET_EOA_REQUIRED",
  "TESTNET_FEE_INVALID",
  "TESTNET_FEE_MODEL_UNAVAILABLE",
  "TESTNET_IMPACT_EXCEEDED",
  "TESTNET_INPUT_BALANCE_LOW",
  "TESTNET_INTENT_INVALID",
  "TESTNET_L2_BUDGET_LOW",
  "TESTNET_MINIMUM_NOT_MET",
  "TESTNET_NATIVE_BALANCE_LOW",
  "TESTNET_NONCE_CHANGED",
  "TESTNET_PREPARE_BUSY",
  "TESTNET_PREPARE_STALE",
  "TESTNET_PREPARE_TIMEOUT",
  "TESTNET_QUOTE_BUSY",
  "TESTNET_QUOTE_INVALID",
  "TESTNET_QUOTE_STALE",
  "TESTNET_QUOTE_TIMEOUT",
  "TESTNET_QUOTE_UNAVAILABLE",
  "TESTNET_RECHECK_BUSY",
  "TESTNET_RECEIPT_BUSY",
  "TESTNET_RECEIPT_TIMEOUT",
  "TESTNET_RECEIPT_STALE",
  "TESTNET_RECEIPT_INVALID",
  "TESTNET_RPC_NOT_CONFIGURED",
  "TESTNET_RPC_UNAVAILABLE",
  "TESTNET_RUNTIME_MISMATCH",
  "TESTNET_STATE_INVALID",
  "TESTNET_SWAP_GAS_INVALID",
  "TESTNET_SWAP_SIMULATION_FAILED",
  "TESTNET_TOTAL_BUDGET_LOW",
  "TESTNET_WRONG_CHAIN",
]);
export const safeTestnetCode = (code: unknown) => typeof code === "string" && codes.has(code) ? code : "TESTNET_BROWSER_UNAVAILABLE";

const actionMessages: Record<string, string> = {
  TESTNET_HISTORICAL_UNVERIFIED: "The original signed approval could not be verified against the supported MetaMask profile. Keep its hash for review.",
  TESTNET_HISTORICAL_TIMEOUT: "Historical approval check timed out. Retry the read explicitly; it does not send another transaction.",
  TESTNET_CONTEXT_UNAVAILABLE: "Original tracking context is unavailable or expired. Keep the hash and recovery record; ask for review before continuing.",
  TESTNET_CONTEXT_HASH_CHANGED: "This hash differs from the original tracked transaction. Keep the original hash and ask for review.",
  TESTNET_RECEIPT_TIMEOUT: "Receipt check timed out. Wait a moment, then check the original transaction again.",
  TESTNET_RECEIPT_BUSY: "Another receipt check is running. Wait for it to finish before checking again.",
  TESTNET_RECEIPT_STALE: "RPC returned stale block data. Wait a moment, then check the original transaction again.",
  TESTNET_RECEIPT_INVALID: "RPC receipt data could not be validated. Keep the original hash and ask for review.",
  TESTNET_BROWSER_BUSY: "The local request budget is busy. Wait a moment before trying an explicit action again.",
  TESTNET_RPC_UNAVAILABLE: "Base Sepolia RPC is unavailable. Check the API terminal and RPC configuration, then retry explicitly.",
  TESTNET_RPC_NOT_CONFIGURED: "Base Sepolia RPC is not configured. Check the API configuration before continuing.",
  TESTNET_BROWSER_ORIGIN: "Open http://127.0.0.1:3020 for this local demo; localhost or another origin is not supported.",
  TESTNET_EOA_REQUIRED: "This wallet uses an unsupported account contract. Use a standard account or the supported MetaMask delegation on Base Sepolia.",
  TESTNET_QUOTE_STALE: "The quote has expired. Request and review a fresh quote before continuing.",
  TESTNET_PREPARE_STALE: "The preparation has expired. Request and review a fresh quote before continuing.",
  TESTNET_NONCE_CHANGED: "The wallet nonce changed. Request and review a fresh quote before continuing.",
};
export function testnetActionMessage(code: string, recovering: boolean) {
  const message = actionMessages[safeTestnetCode(code)] ?? (recovering
    ? "Original transaction check is unavailable. Keep the context and hash; try an explicit receipt check later."
    : "Action unavailable. Request and review a fresh Base Sepolia quote.");
  return recovering ? `${message} Preserve the original transaction; do not send again.` : message;
}
