import { expect, it, vi } from "vitest";
import { handleTestnetLpRequest } from "./testnet-lp-routes";
import { TestnetLpPositionReader, TestnetLpError } from "./testnet-lp-position";
import { lpSource, wallet } from "./testnet-lp.test-helper";
import { TESTNET_NOW } from "./testnet-quote.test-helper";
const url = "http://127.0.0.1:3021/api/v1/testnet/base-sepolia/lp/positions";
const request = (body: unknown) => new Request(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
it("serves only validated bounded LP reads and requires configuration", async () => {
  const body = { chainId: 84532, owner: wallet, cursor: "0", limit: 1 };
  expect((await handleTestnetLpRequest(new Request(url)))?.status).toBe(405);
  expect((await handleTestnetLpRequest(request(body)))?.status).toBe(503);
  const r = new TestnetLpPositionReader(() => lpSource(), () => TESTNET_NOW);
  const response = await handleTestnetLpRequest(request(body), r);
  expect(response?.status).toBe(200); expect((await response!.json()).page.positions).toHaveLength(1);
  expect((await handleTestnetLpRequest(request({ ...body, owner: "bad" }), r))?.status).toBe(400);
  expect((await handleTestnetLpRequest(request({ ...body, extra: "bad" }), r))?.status).toBe(400);
  vi.spyOn(r, "read").mockRejectedValueOnce(new Error("https://rpc.example/PRIVATE_KEY"));
  expect(await (await handleTestnetLpRequest(request(body), r))!.text()).not.toContain("PRIVATE_KEY");
  vi.spyOn(r, "read").mockRejectedValueOnce(new TestnetLpError("TESTNET_LP_BUSY"));
  expect((await handleTestnetLpRequest(request(body), r))?.status).toBe(429);
});
